# Generated by Django 3.2.7 on 2021-09-17 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20210916_1631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='field_name',
            new_name='field_time',
        ),
    ]
