# Generated by Django 3.2.7 on 2021-09-17 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_rename_field_name_userprofile_field_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='field_time',
            new_name='last_updated_time',
        ),
    ]
