# Generated by Django 3.2.7 on 2021-09-17 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0010_auto_20210917_1726'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
