# Generated by Django 3.2.7 on 2021-09-18 08:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0015_auto_20210918_0523'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='repo_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=10), size=2), default=[], size=8),
        ),
    ]
