# Generated by Django 3.2.7 on 2021-09-18 08:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0017_alter_profile_repo_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='repo_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=30), size=2), default=list, size=30),
        ),
    ]
