# Generated by Django 3.2.7 on 2021-09-19 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0018_alter_profile_repo_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
